spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${server.address}:${server.port}/eureka/
  server:
    enable-self-preservation: true
server:
  port: 1111
  address: 10.108.26.220
info:
  description: consumer service for demo-use


